### ISSUE TITLE
Add support for `key` function

### ISSUE THREAD

**Issue by secrettriangle** [javascript/sorted-array#2]

**Comment by aaditmshah** [comment]
What is the `key` function supposed to do?

**Comment by secrettriangle** [comment]
My use case is something like this: I have an array of objects, each containing a key `timestamp_ms`. Currently, if I want to use `SortedArray`, I'd have to map the array to get `timestamp_ms`, and I would only be able to insert new `timestamp_ms`s as opposed to the actual objects that contain the `timestamp_ms`. A `key` function might look like `function (val) { return val.timestamp_ms; }`. That way I'd be able to use my array as-is, and insert items as they are without loss of information.
